# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Mapillary2QGIS
                                 A QGIS plugin
 This piece of python code will download Mapillary data in QGIS canvas as a Point Vector layer.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2025-08-14
        copyright            : (C) 2025 by Quang Huy NGUYEN
        email                : quanghuy.nguyen@mail.polimi.it
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Quang Huy NGUYEN'
__date__ = '2025-08-14'
__copyright__ = '(C) 2025 by Quang Huy NGUYEN'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Mapillary2QGIS class from file Mapillary2QGIS.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Mapillary2QGIS import Mapillary2QGISPlugin
    return Mapillary2QGISPlugin()
